version: '3.8'

services:
  # VPN Bot Application
  vpn_bot:
    image: seriousnuts/vpn_bot:main
    container_name: vpn_bot_app_prod
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - vpn_bot_network

networks:
  vpn_bot_network:
    driver: bridge
